
-- KalaKrit — Complete Supabase Schema Setup
-- For Team Collaboration
--
-- INSTRUCTIONS:
-- 1. Go to Supabase Dashboard: https://app.supabase.com
-- 2. Select your project → SQL Editor
-- 3. Create a new query
-- 4. Copy-paste THIS ENTIRE SCRIPT into the editor
-- 5. Click "Run" to execute all at once
--
-- This script sets up:
--   - profiles table (user profile data)
--   - products table (marketplace listings)
--   - Row-level security policies
--   - Auto-profile trigger on signup
--   - Updated_at auto-update triggers
--
-- ============================================================

-- 1. PROFILES TABLE
-- Stores user profile info: name, craft, location, language
-- Linked to Supabase auth.users via id foreign key
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  phone TEXT,
  craft TEXT,
  location TEXT,
  language TEXT DEFAULT 'en',
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable row-level security on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Anyone can read all profiles (needed for marketplace to show artisan info)
CREATE POLICY "Profiles are viewable by everyone"
  ON public.profiles
  FOR SELECT
  TO PUBLIC
  USING (true);

-- RLS Policy: Users can only update their own profile
CREATE POLICY "Users can update own profile"
  ON public.profiles
  FOR UPDATE
  USING (auth.uid() = id);

-- RLS Policy: Users can insert their own profile
CREATE POLICY "Users can insert own profile"
  ON public.profiles
  FOR INSERT
  WITH CHECK (auth.uid() = id);


-- 2. PRODUCTS TABLE
-- Main product listings created by artisans via voice-to-listing feature
-- Includes AI-generated storytelling fields
CREATE TABLE IF NOT EXISTS public.products (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Core product info
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  tags TEXT[] DEFAULT '{}',
  materials TEXT[] DEFAULT '{}',
  highlights TEXT[] DEFAULT '{}',
  suggested_price NUMERIC DEFAULT 0,
  images TEXT[] DEFAULT '{}',
  
  -- Voice input and language
  transcript TEXT,
  language TEXT,
  
  -- Publication status
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  
  -- AI Storytelling fields (generated by Gemini API)
  story_title TEXT,
  craft_heritage TEXT,
  how_its_made TEXT,
  why_unique TEXT,
  artisan_narrative TEXT,
  
  -- Product stats
  views_count INTEGER DEFAULT 0,
  orders_count INTEGER DEFAULT 0,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable row-level security on products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Published products visible to everyone (marketplace buyers)
-- Draft/archived products only visible to the owner (artisan)
CREATE POLICY "Published products are viewable by everyone"
  ON public.products
  FOR SELECT
  USING (status = 'published' OR auth.uid() = user_id);

-- RLS Policy: Artisans can insert their own products
CREATE POLICY "Users can insert own products"
  ON public.products
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- RLS Policy: Artisans can update their own products
CREATE POLICY "Users can update own products"
  ON public.products
  FOR UPDATE
  USING (auth.uid() = user_id);

-- RLS Policy: Artisans can delete their own products
CREATE POLICY "Users can delete own products"
  ON public.products
  FOR DELETE
  USING (auth.uid() = user_id);


-- 3. AUTO-CREATE PROFILE ON SIGNUP
-- This trigger automatically creates a profile row when a new user signs up
-- Profile data comes from auth.raw_user_meta_data set in SignUp function
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (
    id,
    full_name,
    phone,
    craft,
    location,
    language
  )
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'phone',
    NEW.raw_user_meta_data->>'craft',
    NEW.raw_user_meta_data->>'location',
    COALESCE(NEW.raw_user_meta_data->>'language', 'en')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing trigger if any, then create new one
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 4. UPDATED_AT AUTO-UPDATE TRIGGERS
-- Automatically sets updated_at to current timestamp on any row update
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for products table
DROP TRIGGER IF EXISTS products_updated_at ON public.products;
CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- Trigger for profiles table
DROP TRIGGER IF EXISTS profiles_updated_at ON public.profiles;
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


-- ============================================================
-- SETUP COMPLETE!
--
-- Next steps:
-- 1. Go to Authentication → Settings
-- 2. Enable "Email" provider
-- 3. Copy your VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY
--    and add to .env file in the frontend
--
-- API Client Usage:
-- - getSession() → Get current logged-in user
-- - signUp() → Register new artisan (creates profile via trigger)
-- - signIn() → Login with email & password
-- - signOut() → Logout
--
-- Database Queries:
-- - SELECT full_name FROM profiles WHERE id = user_id
-- - SELECT * FROM products WHERE status = 'published'
-- - SELECT * FROM products WHERE user_id = auth.uid()
--
-- ============================================================
